USE [master]
GO

/****** Object:  Database [kskVue]    Script Date: 12.03.2020 10:01:50 ******/
CREATE DATABASE [kskVue]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'kskPHP', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\kskVue.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'kskPHP_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\kskVue_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [kskVue] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [kskVue].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [kskVue] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [kskVue] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [kskVue] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [kskVue] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [kskVue] SET ARITHABORT OFF 
GO

ALTER DATABASE [kskVue] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [kskVue] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [kskVue] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [kskVue] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [kskVue] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [kskVue] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [kskVue] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [kskVue] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [kskVue] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [kskVue] SET  DISABLE_BROKER 
GO

ALTER DATABASE [kskVue] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [kskVue] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [kskVue] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [kskVue] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [kskVue] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [kskVue] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [kskVue] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [kskVue] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [kskVue] SET  MULTI_USER 
GO

ALTER DATABASE [kskVue] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [kskVue] SET DB_CHAINING OFF 
GO

ALTER DATABASE [kskVue] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [kskVue] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [kskVue] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [kskVue] SET  READ_WRITE 
GO

